name: Cleanup

# clean up old artifacts and resources
on:
  schedule:
    - cron: '0 3 * * 0'  # sundays at 3am
  workflow_dispatch:

jobs:
  cleanup-artifacts:
    name: Clean up old artifacts
    runs-on: ubuntu-latest
    
    steps:
    - name: Delete old workflow artifacts
      uses: actions/github-script@v6
      with:
        script: |
          // keep artifacts for 30 days
          const cutoffDate = new Date();
          cutoffDate.setDate(cutoffDate.getDate() - 30);
          
          const artifacts = await github.rest.actions.listArtifactsForRepo({
            owner: context.repo.owner,
            repo: context.repo.repo,
            per_page: 100
          });
          
          for (const artifact of artifacts.data.artifacts) {
            const createdAt = new Date(artifact.created_at);
            if (createdAt < cutoffDate) {
              console.log(`Deleting artifact: ${artifact.name} (${artifact.created_at})`);
              await github.rest.actions.deleteArtifact({
                owner: context.repo.owner,
                repo: context.repo.repo,
                artifact_id: artifact.id
              });
            }
          }
          
  cleanup-packages:
    name: Clean up old packages
    runs-on: ubuntu-latest
    
    steps:
    - name: Delete old container images
      uses: actions/delete-package-versions@v4
      with:
        package-name: 'quote-api'
        package-type: 'container'
        min-versions-to-keep: 5  # keep last 5 versions
        delete-only-untagged-versions: true
